# Generated by Django 6.0 on 2026-01-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_points',
            field=models.IntegerField(default=0),
        ),
    ]
